-- GWE bid import (18 solicitations). Run AFTER gwe_leads_bids.sql + gwe_bids_extend.sql.
-- Idempotent: skips a bid if the same solicitation_no already exists.

insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Janitorial Services in Alameda and San Francisco County', 'Janitorial', 'PASS', 'Caltrans janitorial; Alameda Co = P2 ~50mi; mandatory job-walk 08/10 not missed; 20 days to close.', '04A7443', 'State of California - Caltrans (Dist 04)', 'State', 'Alameda', 'Alameda & SF County', 'prospect', '2026-08-20'::date, 'Y - Mandatory Job-Walk 08/10/2026 (3 sessions: 8:45 / 10:30 / 12:30 PM PDT)', '2026-08-10'::date, '2026-08-11'::date, 'https://caleprocure.ca.gov/event/2660/04A7443', 'Angel Cervantes Jr.', '916-201-3927', 'Angel.Cervantes.Jr@dot.ca.gov', 'Caltrans Dist 04 janitorial: all labor, tools, materials, supplies, equipment at Alameda (1993 Marina Blvd + others) & SF sites. Term 10/01/2026-09/30/2027.', '1) Register/log in at caleprocure.ca.gov. 2) Open Event 04A7443. 3) Download IFB + attachments. 4) Attend a mandatory 08/10 job-walk. 5) Submit questions by 08/11 5:00 PM. 6) Submit bid electronically before 08/20 2:00 PM PDT.', 'Attend ONE mandatory 08/10 session (8:45/10:30/12:30). Email Angel.Cervantes.Jr@dot.ca.gov or call 916-201-3927 to confirm session + pre-registration. Bring ID, sign attendance sheet (required to bid).', 'Subject: GWE - Intent to Bid, 04A7443 Janitorial Services (Caltrans Dist 04)

Hi Angel,

Great Way Environmental is a licensed commercial janitorial contractor serving Alameda County. We''re preparing a response to 04A7443 - Janitorial Services in Alameda and San Francisco County (closing 08/20).

Could you confirm which of the 08/10 mandatory job-walk sessions (8:45 / 10:30 / 12:30) we should attend and whether pre-registration is required? Want to make sure our submission is complete.

Appreciate it,
Fernando Gonzalez
Great Way Environmental'
where not exists (select 1 from bids where solicitation_no = '04A7443');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Parking Garage Cleaning Services', 'Janitorial', 'PASS', 'County of Alameda issuer; P2 + GWE licensed (Dublin/Oakland/Fremont); ~50mi; prebid recommended (not mandatory); 31 days to close.', 'RFQ 902758', 'County of Alameda (GSA Parking Division)', 'County', 'Alameda', 'Alameda County', 'prospect', '2026-08-31'::date, 'N - Prebid Conference 08/06/2026 1:00 PM PDT (RECOMMENDED, not mandatory)', '2026-08-06'::date, '2026-08-07'::date, 'https://procurement.opengov.com/portal/acgov/projects/287567', 'Ning Peng', '510-208-9636', 'ning.peng2@acgov.org', 'Routine cleaning, maintenance & upkeep of 4 County-owned public parking garages (Alameda County GSA Parking Division).', '1) procurement.opengov.com/portal/acgov - create/log in vendor account. 2) Open project 287567 (RFQ 902758), click Follow. 3) Download RFQ + response template. 4) (Optional) attend 08/06 prebid. 5) Questions by 08/07 5:00 PM. 6) Submit quote in OpenGov before 08/31 2:00 PM PDT.', 'Prebid RECOMMENDED only (08/06 1:00 PM) - not required to bid. Confirm link: email ning.peng2@acgov.org or call 510-208-9636, or check OpenGov project 287567.', 'Subject: GWE - Intent to Bid, RFQ 902758 Parking Garage Cleaning

Hi Ning,

Great Way Environmental is a licensed commercial cleaning contractor serving Alameda County. We''re preparing a quote for RFQ 902758 - Parking Garage Cleaning Services (closing 08/31).

Could you confirm the required insurance & bond limits and the vendor-registration step in OpenGov? Want to make sure our submission is complete.

Appreciate it,
Fernando Gonzalez
Great Way Environmental'
where not exists (select 1 from bids where solicitation_no = 'RFQ 902758');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Janitorial Services', 'Janitorial', 'WALK', 'CHP (State), Tulare County ~150mi (>120mi radius). Scope OK, location fail.', '26C481003', 'State of California - CHP', 'State', 'Tulare', 'Tulare County', 'prospect', '2026-08-18'::date, 'N - Prebid 08/06 10:00 AM (not marked mandatory)', '2026-08-06'::date, '2026-08-12'::date, 'https://caleprocure.ca.gov/pages/Events-BS3/event-search.aspx', null, '800-735-2929', null, 'Janitorial 8am-4pm at CHP site; schedule with on-site contact; check-in/checkout each visit.', 'Cal eProcure: register/log in, find Event 26C481003 via event-search, download package, questions by 08/12, submit before 08/18 2:00 PM.', 'Prebid 08/06 10:00 AM - call 800-735-2929 to confirm location & whether attendance required.', null
where not exists (select 1 from bids where solicitation_no = '26C481003');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Small Business Solicitation for After-Hours Janitorial Services', 'Janitorial', 'WALK', 'DMV (State), Kern County ~230mi, outside radius. Mandatory prebid 08/18. Location fail.', '26-109', 'State of California - DMV', 'State', 'Kern', 'Kern County', 'prospect', '2026-09-01'::date, 'Y - Prebid 08/18 9:00 AM PDT (Mandatory)', '2026-08-18'::date, '2026-08-25'::date, 'https://caleprocure.ca.gov/pages/index.aspx', 'Anne Mearlon', '916-818-2849', 'anne.mearlon@dmv.ca.gov', 'After-hours janitorial for DMV office ~2,763 sq ft; Mon-Fri after hours, excl. holidays. Small Business preference.', 'Cal eProcure: register/log in, find event 26-109, attend mandatory prebid 08/18, questions by 08/25, submit before 09/01 2:00 PM.', 'Mandatory prebid 08/18 9:00 AM - email anne.mearlon@dmv.ca.gov or call 916-818-2849 to RSVP; must sign in to be eligible.', null
where not exists (select 1 from bids where solicitation_no = '26-109');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'IFB Janitorial Services, Imperial County', 'Janitorial', 'WALK', 'Caltrans (State), Imperial County ~500mi, far outside radius. Location fail.', '11A4408', 'State of California - Caltrans', 'State', 'Imperial', 'Imperial County', 'prospect', '2026-08-06'::date, 'N - none listed', null::date, null::date, 'https://caleprocure.ca.gov/pages/index.aspx', 'Tim Murphy', '279-234-2662', 'Timothy.murphy@dot.ca.gov', 'Caltrans janitorial, Imperial County. No specs on BidNet notice.', 'Cal eProcure: register/log in, locate 11A4408, contact Tim Murphy for specs, submit before 08/06 2:00 PM.', 'No walkthrough listed. If pursued, call Tim Murphy 279-234-2662 to confirm none required.', null
where not exists (select 1 from bids where solicitation_no = '11A4408');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Janitorial Services', 'Janitorial', 'WALK', 'Special District, Santa Barbara ~280mi + mandatory prebid 07/29 already passed. Territory + walkthrough fail.', 'SBMTD IFB', 'Santa Barbara Metro Transit District', 'Special District', 'Santa Barbara', 'Santa Barbara County', 'prospect', '2026-08-12'::date, 'Y - Prebid 07/29 9:00 AM (Mandatory) - ALREADY PASSED', '2026-07-29'::date, '2026-08-05'::date, 'http://sbmtd.gov/about/doing-business/', 'Valerie White', '805-963-3364 ext.244', 'purchasing@sbmtd.gov', 'Daily janitorial at 3 SBMTD facilities; 1-yr base + four 1-yr options (5-yr max).', 'SBMTD ''Doing Business'' page - download IFB, submit per instructions. NOTE: mandatory prebid passed - likely ineligible.', 'Mandatory prebid 07/29 already passed. Email purchasing@sbmtd.gov to ask if late entry possible.', null
where not exists (select 1 from bids where solicitation_no = 'SBMTD IFB');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Countywide Janitorial Services', 'Janitorial', 'WALK', 'County of Orange ~380mi, outside radius. Territory fail.', 'RFP-017-2988904-JC', 'County of Orange', 'County', 'Orange', 'Orange County', 'prospect', '2026-10-27'::date, 'Y - 7 Mandatory Job-Walks 08/04-09/22 (5:00 AM PDT)', '2026-08-04'::date, '2026-10-06'::date, 'https://procurement.opengov.com/portal/ocgov/projects/231686', null, '714-567-7314', null, 'Countywide janitorial for secure/restricted facilities (background clearance, badging, security coordination).', 'OpenGov ocgov project 231686: register, download RFP, attend a mandatory job-walk, questions by 10/06, submit before 10/27 11:00 AM.', 'Pick one of 7 mandatory job-walk dates; call 714-567-7314 to RSVP & get address; sign in to be eligible.', null
where not exists (select 1 from bids where solicitation_no = 'RFP-017-2988904-JC');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Baldwin Park Janitorial Services', 'Janitorial', 'WALK', 'Cal OES (State) but site Baldwin Park (LA Co) ~350mi; mandatory prebid 07/28 passed; closes 08/04. Location + walkthrough fail.', 'A261017467', 'State of California - Cal OES', 'State', 'Los Angeles', 'Baldwin Park (LA Co)', 'prospect', '2026-08-04'::date, 'Y - Prebid 07/28 10:00 AM (Mandatory) - ALREADY PASSED', '2026-07-28'::date, '2026-07-29'::date, 'https://caleprocure.ca.gov/event/0690/0000039821', 'Carrie Koch', '916-369-4258', 'carrie.koch@caloes.ca.gov', 'Weekly janitorial: trash/liners, restroom sanitation, floor care, dusting, touchpoint sanitizing, breakroom; monthly high dusting, windows.', 'Cal eProcure event 0000039821. NOTE: mandatory prebid passed - likely ineligible.', 'Mandatory prebid 07/28 already passed. Contact Carrie Koch 916-369-4258 re: late-entry only.', null
where not exists (select 1 from bids where solicitation_no = 'A261017467');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Custodial/Janitorial Services for the City''s Public Safety Building', 'Janitorial', 'WALK', 'City of Garden Grove (not P1), Orange Co ~380mi; mandatory tour 07/27-28 passed. Territory + walkthrough fail.', 'S-1396', 'City of Garden Grove', 'City', 'Orange', 'Orange County', 'prospect', '2026-08-14'::date, 'Y - Mandatory tour 07/27 OR 07/28 2:00 PM - ALREADY PASSED', '2026-07-27'::date, '2026-08-02'::date, 'https://vendors.planetbids.com/portal/15118/bo/bo-search', 'Sandra Segawa', null, 'Sandras@ggcity.org', 'Custodial/janitorial for City Public Safety Building; tour required before work plan + cost proposal.', 'PlanetBids portal 15118: register, download docs, submit. NOTE: mandatory tour passed - likely ineligible.', 'Mandatory tour 07/27/28 already passed. Email Sandras@ggcity.org re: eligibility.', null
where not exists (select 1 from bids where solicitation_no = 'S-1396');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Janitorial Services for Various City Facilities', 'Janitorial', 'WALK', 'City of Murrieta (not P1), Riverside Co ~440mi; mandatory job-walk 07/27 passed. Territory + walkthrough fail.', 'MSD 26-011', 'City of Murrieta', 'City', 'Riverside', 'Riverside County', 'prospect', '2026-08-12'::date, 'Y - Mandatory Job-Walk 07/27 8:30 AM - ALREADY PASSED', '2026-07-27'::date, '2026-08-03'::date, 'https://vendors.planetbids.com/portal/17992/bo/bo-detail/144027', 'Ken Jones', '951-461-6402', 'kjones@murrietaca.gov', 'Janitorial for various City of Murrieta facilities; single contractor; all labor, equipment, some supplies, supervision.', 'PlanetBids portal 17992 (bid 144027). NOTE: mandatory job-walk passed - likely ineligible.', 'Mandatory job-walk 07/27 already passed. Contact Ken Jones 951-461-6402 re: late-entry only.', null
where not exists (select 1 from bids where solicitation_no = 'MSD 26-011');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Janitorial Services (Sonoma County Library)', 'Janitorial', 'WALK', 'Special District, Sonoma County not P1/P2 & GWE not licensed there. Territory fail.', 'SCL RFP', 'Sonoma County Library', 'Special District', 'Sonoma', 'Sonoma County', 'prospect', '2026-08-07'::date, 'N - none listed', null::date, '2026-07-24'::date, 'https://sonomalibrary.org/about/contracting-opportunities', 'Clint Yeager', null, 'cyeager@sonomalibrary.org', 'Janitorial for 12 regional libraries, 2 community locations, 1 admin building; all labor/supervision/equipment/supplies.', 'Sonoma Library Contracting Opportunities page - download RFP, submit before 08/07 5:00 PM.', 'No walkthrough. If pursued, email cyeager@sonomalibrary.org to confirm submission format.', null
where not exists (select 1 from bids where solicitation_no = 'SCL RFP');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Janitorial Services (Salesforce Transit Center)', 'Janitorial', 'WALK', 'Special District, San Francisco not in P2 list & GWE not licensed in SF. Territory fail.', '26-06', 'Transbay Joint Powers Authority', 'Special District', 'San Francisco', 'San Francisco County', 'prospect', '2026-08-07'::date, 'N - none listed', null::date, '2026-07-15'::date, 'https://www.tjpa.org/about-tjpa/doing-business/contract-opportunities/ifb-26-06-janitorial-services', null, '415-597-4620', 'procurement@tjpa.org', 'Janitorial for Salesforce Transit Center, Salesforce Park & infrastructure: ramps, corridors, lobbies, restrooms, public spaces.', 'TJPA Contract Opportunities page (IFB 26-06) - download docs, submit before 08/07 2:00 PM.', 'No walkthrough. If pursued, email procurement@tjpa.org to confirm submission logistics.', null
where not exists (select 1 from bids where solicitation_no = '26-06');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Bus Terminal Janitorial Services', 'Janitorial', 'WALK', 'Special District, Kern County (Bakersfield) ~230mi, outside radius. Location fail.', 'G164', 'Golden Empire Transit District', 'Special District', 'Kern', 'Kern County', 'prospect', '2026-08-10'::date, 'N - Site walk 07/09-15 by appointment (non-mandatory) - window passed', null::date, '2026-07-22'::date, 'https://www.getbus.org/procurement-and-other-terms/', 'Solana Roberts', '661-324-9874', 'sroberts@getbus.org', 'Daily janitorial for GET bus terminal facilities; clean/sanitize restrooms, maintain fixtures, emergency cleanup.', 'GET Procurement page - download docs, submit before 08/10 1:00 PM.', 'Site walk (07/09-15, non-mandatory) passed. Call Solana Roberts 661-324-9874 re: a late walk.', null
where not exists (select 1 from bids where solicitation_no = 'G164');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'CUSTODIAL SERVICES', 'Janitorial', 'WALK', 'CSU (State), Monterey County ~120mi (borderline) + mandatory prebid 07/06 passed. Walkthrough fail.', 'MB-2026005', 'CSU Monterey Bay', 'State (CSU)', 'Monterey', 'Monterey County', 'prospect', '2026-08-17'::date, 'Y - Prebid 07/06 8:30 AM (Mandatory) - ALREADY PASSED', '2026-07-06'::date, '2026-07-20'::date, 'https://vendors.planetbids.com/portal/26036/bo/bo-detail/143396', 'Marcus Medina', '831-582-4073', 'marcmedina@csumb.edu', 'Custodial services for CSU Monterey Bay & auxiliaries; all aspects of custodial.', 'PlanetBids portal 26036 (bid 143396). NOTE: mandatory prebid passed - likely ineligible.', 'Mandatory prebid 07/06 already passed. Email marcmedina@csumb.edu re: eligibility.', null
where not exists (select 1 from bids where solicitation_no = 'MB-2026005');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Office & Site Cleaning Services', 'Janitorial', 'WALK', 'Special District, San Diego Co ~500mi + mandatory prebid 07/09 passed + closes 07/31. Location + walkthrough fail.', 'AM-27-01', 'San Diego Housing Commission', 'Special District', 'San Diego', 'San Diego County', 'prospect', '2026-07-31'::date, 'Y - Prebid 07/09 10:00 AM (Mandatory) - ALREADY PASSED', '2026-07-09'::date, '2026-07-15'::date, 'https://vendors.planetbids.com/portal/39471/bo/bo-detail/143590', 'Mark Matsunaga', '619-578-7540', 'Markm@sdhc.org', 'Office & site cleaning for SD Housing Commission. No specs on notice.', 'PlanetBids portal 39471 (bid 143590). NOTE: mandatory prebid passed & closes 07/31 - not actionable.', 'Mandatory prebid 07/09 already passed & closed. Not bookable.', null
where not exists (select 1 from bids where solicitation_no = 'AM-27-01');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'Garage and Downtown Pressure Washing Services', 'Property Care', 'WALK', 'City of Mountain View (not P1), Santa Clara not a P2 county. Territory fail. Adjacent (pressure washing).', 'R270455', 'City of Mountain View', 'City', 'Santa Clara', 'Santa Clara County', 'prospect', '2026-08-31'::date, 'N - none listed', null::date, '2026-08-05'::date, 'https://vendors.planetbids.com/portal/47527/bo/bo-detail/144333', 'Sunny Nguyen', '650-903-6324', 'sunny.nguyen@mountainview.gov', 'High/low pressure washing of garage & downtown surfaces; remove dirt, gum, residue, stains, debris. Term thru 06/30/2027.', 'PlanetBids portal 47527 (bid 144333) - register, download RFB, questions by 08/05, submit before 08/31 2:00 PM.', 'No walkthrough. If territory expands, email sunny.nguyen@mountainview.gov re: site visit & insurance/bond limits.', null
where not exists (select 1 from bids where solicitation_no = 'R270455');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'As-Needed Unit Turnover Cleaning and Carpet Cleaning Service', 'Janitorial', 'WALK', 'Alameda Co = P2 & licensed, BUT scope is residential-unit turnover (residential DROP rule). Flagged.', '2026-RFP-AHA-PO-003', 'Alameda City Housing Authority', 'Special District', 'Alameda', 'Alameda County', 'prospect', '2026-08-17'::date, 'N - Prebid 08/05 10:30 AM (RECOMMENDED)', '2026-08-05'::date, '2026-08-07'::date, 'https://alamedahsg.bonfirehub.com/opportunities/245757', 'Radha Mehta', '510-747-4318', 'rmehta@alamedahsg.org', 'On-call turnover cleaning of vacant residential units across multi-family properties incl. carpet cleaning. RESIDENTIAL - dropped per rule (flagged).', 'Bonfire (alamedahsg.bonfirehub.com opportunity 245757) - register free, download RFP, questions by 08/07, submit before 08/17 4:00 PM.', 'Recommended prebid 08/05 10:30 AM - email rmehta@alamedahsg.org or call 510-747-4318. Not required to bid.', null
where not exists (select 1 from bids where solicitation_no = '2026-RFP-AHA-PO-003');
insert into bids (project, service_type, gate, reason, solicitation_no, issuer, issuer_type, county, city, status, due_date, walkthrough, walkthrough_date, questions_due, portal_link, contact_name, contact_phone, contact_email, scope, steps_apply, steps_walk, intent_email)
select 'On-call Residential Unit Cleaning Services', 'Janitorial', 'WALK', 'Marin Co = P2 & licensed, BUT scope explicitly residential unit cleaning (residential DROP rule) AND closes 08/04. Flagged.', '2026-002', 'Marin Housing Authority', 'Special District', 'Marin', 'Marin County', 'prospect', '2026-08-04'::date, 'N - none listed', null::date, '2026-07-31'::date, 'https://procurement.opengov.com/portal/marinhousing/projects/284954', 'Chris Barta', '415-544-5000', 'cbarta@marinhousing.org', 'On-call residential unit cleaning at MHA-owned/managed properties; all labor, supervision, equipment. RESIDENTIAL - dropped per rule (flagged).', 'OpenGov (procurement.opengov.com/portal/marinhousing project 284954) - register, download IFB, submit sealed bid before 08/04 11:59 PM.', 'No walkthrough. If taking residential, email cbarta@marinhousing.org to confirm sealed-bid format.', null
where not exists (select 1 from bids where solicitation_no = '2026-002');
